# Generated by Django 4.0.1 on 2022-01-31 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=80)),
                ('cpf', models.CharField(max_length=14)),
                ('dt_nascimento', models.DateField()),
                ('genero', models.CharField(max_length=17)),
                ('telefone', models.CharField(max_length=14)),
                ('email', models.CharField(max_length=20)),
                ('pais', models.CharField(max_length=50)),
                ('cidade', models.CharField(max_length=50)),
                ('bairro', models.CharField(max_length=50)),
                ('numero', models.IntegerField()),
            ],
        ),
    ]
