# Generated by Django 4.0.1 on 2022-01-31 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='dt_nascimento',
            new_name='data_de_nascimento',
        ),
    ]
